fix: fe36764 broke ROOT_COMPAT when more than 1 device was connected

diff --git a/adebar-cli b/adebar-cli
--- a/adebar-cli
+++ b/adebar-cli
@@ -249,17 +249,6 @@ if [ -n "${SERIAL}" ]; then
   ADBOPTS="-s ${SERIAL}"
 fi
 
-# Verify root access
-_testroot=$(adb shell su -c 'date' 2>/dev/null)
-if [[ $? -eq 0 ]]; then
-  HAVE_ROOT=1
-else
-  HAVE_ROOT=0
-  [[ ROOT_BACKUP -gt 0 ]] && { ROOT_BACKUP=0; echo -e "$(ansi_code "'su' not found on device, resetting ROOT_BACKUP to 0" "yellow")"; }
-  [[ ROOT_COMPAT -gt 0 ]] && { ROOT_COMPAT=0; echo -e "$(ansi_code "'su' not found on device, resetting ROOT_COMPAT to 0" "yellow")"; }
-  [[ ROOT_PMDISABLE -gt 0 ]] && { ROOT_PMDISABLE=0; echo -e "$(ansi_code "'su' not found on device, resetting ROOT_PMDISABLE to 0" "yellow")"; }
-fi
-
 # Check output directory and create it if it does not exist
 if [ -n "${STORAGE_BASE}" ]; then
   OUTDIR="${STORAGE_BASE}/${OUTDIR}"
@@ -307,6 +296,19 @@ declare -a userApps # list of package names
 declare -a sysApps
 declare -a disApps
 declare -a uninstApps
+
+# Verify root access
+_testroot=$(adb $ADBOPTS shell su -c 'date' 2>/dev/null)
+if [[ $? -eq 0 ]]; then
+  HAVE_ROOT=1
+  doProgress "Root access available." 2
+else
+  HAVE_ROOT=0
+  doProgress "Root access unavailable." 2
+  [[ ROOT_BACKUP -gt 0 ]] && { ROOT_BACKUP=0; echo -e "$(ansi_code "'su' not found on device, resetting ROOT_BACKUP to 0" "yellow")"; }
+  [[ ROOT_COMPAT -gt 0 ]] && { ROOT_COMPAT=0; echo -e "$(ansi_code "'su' not found on device, resetting ROOT_COMPAT to 0" "yellow")"; }
+  [[ ROOT_PMDISABLE -gt 0 ]] && { ROOT_PMDISABLE=0; echo -e "$(ansi_code "'su' not found on device, resetting ROOT_PMDISABLE to 0" "yellow")"; }
+fi
 
 
 #
